### ISSUE TITLE
Cannot fetch gcr.io image with docker_image.py

### ISSUE THREAD

**Issue by pombredanne** [fishilico/shared#1]
Hi Nicolas:
I cannot seem to be able to fetch gcr images... nor a quay.io one:
```
$ python docker_image.py   -o fetc gcr.io/distroless/static
[INFO] Downloading gcr.io/distroless/static:latest...
[ERROR] Unable to retrieve the manifest of 'gcr.io/distroless/static':'latest': HTTP error 401
[ERROR] ... Response JSON: {'errors': [{'code': 'UNAUTHORIZED', 'message': 'authentication required', 'detail': [{'Type': 'repository', 'Class': '', 'Name': 'gcr.io/distroless/static', 'Action': 'pull'}]}]}
Traceback (most recent call last):
  File "docker_image.py", line 511, in <module>
    main()
  File "docker_image.py", line 507, in main
    registry.download_image(image, tag, args.output)
  File "docker_image.py", line 393, in download_image
    manifest = self.get_manifest(image_name, tag_name)
  File "docker_image.py", line 253, in get_manifest
    raise ValueError("HTTP error {}".format(response.status_code))
ValueError: HTTP error 401
```
or:
```
$ python docker_image.py  -o fetc  quay.io/calico/node -l
[ERROR] Unable to retrieve the tags of image 'quay.io/calico/node': HTTP error 401
[ERROR] ... Response JSON: {'errors': [{'code': 'UNAUTHORIZED', 'message': 'authentication required', 'detail': [{'Type': 'repository', 'Class': '', 'Name': 'quay.io/calico/node', 'Action': 'pull'}]}]}
Traceback (most recent call last):
  File "docker_image.py", line 511, in <module>
    main()
  File "docker_image.py", line 479, in main
    tags = registry.list_tags(image)
  File "docker_image.py", line 226, in list_tags
    raise ValueError("HTTP error {}".format(response.status_code))
ValueError: HTTP error 401
```

If I use a vanilla docker on Ubuntu 16.04 things work OK:
```
$ uname -a
Linux test 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
pombredanne@staging:~$ docker --version
Docker version 18.09.7, build 2d0083d



$ sudo docker pull gcr.io/distroless/static:latest
latest: Pulling from distroless/static
9ff2acc3204b: Pull complete 
Digest: sha256:c6d5981545ce1406d33e61434c61e9452dad93ecd8397c41e89036ef977a88f4
Status: Downloaded newer image for gcr.io/distroless/static:latest
```

Also I am planning to reuse your fine code in this library: https://github.com/nexB/conan/pull/20
I can vendor (and possibly fork? it) or you could promote it as it's own top level package and repo, deployed @ Pypi? (Conan will be released at Pypi too)

**Comment by fishilico** [comment]
Hi,
Thanks for your bug report. There was indeed an incompatibility with gcr.io and quay.io registries, where `ping` API always fails when the `scope` parameter is empty. I added a commit to fix this.

Now the following commands work:
```
python3 docker_image.py -r gcr.io distroless/static -l
python3 docker_image.py -r quay.io calico/node -l
```
(Please note that my script does not split the registry name from the image reference automatically and that you need to use option `-r` for this)

> Also I am planning to reuse your fine code in this library: nexB/conan#20

I am fine with it. Please be aware that my code is "Proof-of-concept level", and I mainly wrote it in order to be able to download Microsoft Docker images without using Windows (`docker pull` and `podman pull` do not work because both these commands check the OS compatibility).

> I can vendor (and possibly fork? it) or you could promote it as it's own top level package and repo, deployed @ Pypi? (Conan will be released at Pypi too)

As it is more a PoC that anything else, I do not wish to support it nor package it on itself. If you want to do this, feel free to do this and please add a reference to me ("`Nicolas Iooss (https://github.com/fishilico)`") and/or to the original file (https://github.com/fishilico/shared/blob/f342f7b92c5449f1f622afce5582ade235f3bb9c/python/network/docker_image.py).

**Comment by pombredanne** [comment]
@fishilico thank you ++ :bow:

**Comment by pombredanne** [comment]
Here is how I integrated your code... this is vendored and not modified for now. If I have fixes, I will try to push them back to you.
https://github.com/nexB/conan/tree/python3-port/src/conan/fetch
